{% set name = "PACKAGE_NAME" %}
{% set version = "0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/package_name-{{ version }}.tar.gz
  sha256: 6791bd670efd086c99706c6dd82ba2d4dcee397a575c51f257398c8028f616be

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - package_name
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yourself/package_name
  summary: Package Description
  license: Noweb
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - alwayslove2013
